name: nasa-nex
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask
  - distributed
  - fastparquet 
  - gcsfs
  - git
  - ipython 
  - h5netcdf
  - h5py
  - h5pyd
  - kerchunk
  - mamba
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - s3fs
  - xarray
  - xarray-datatree
  - xmip
  - zarr

  - pip:
      - git+https://github.com/pangeo-forge/pangeo-forge-recipes
      - pangeo-forge-runner
      - "apache-beam[interactive, dataframe]"

