name: nasa-nex
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dask[complete]==2023.10.0
  - fastparquet==2023.10.1
  - gcsfs==2023.10.0
  - git==2.42.0
  - geopandas==0.14.0
  - h5netcdf==1.2.0
  - coiled==1.1.5
  - kerchunk==0.2.2
  - h5py==3.10.0
  - h5pyd==0.16.0
  - ipython==8.16.1
  - ipykernel==6.26.0
  - mamba==1.5.2
  - matplotlib==3.8.0
  - netcdf4==1.6.5
  - numpy==1.26.0
  - pandas==2.1.2
  - pip==23.3.1
  - s3fs==2023.10.0
  - xarray
  - xarray-datatree==0.0.12
  - xmip==0.7.1
  - xarrayutils==2.0.0
  - xgcm==0.6.1
  - zarr==2.16.1
  - xclim
  - sparse
  - pint==0.22

  - pip:
      - thermofeel==1.3.0
