name: nasa-nex
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dask
  - distributed
  - fastparquet
  - gcsfs
  - git
  - ipython
  - geopandas
  - h5netcdf
  - h5py
  - h5pyd
  - mamba
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - s3fs
  - xarray
  - xarray-datatree
  - xmip
  - zarr

  - pip:
      - git+https://github.com/fsspec/kerchunk
      - "dask[complete]"
      - coiled
      - xclim==0.44.0
      - sparse
      - pint==0.22
      - thermofeel
